# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landr', '0003_auto_20160923_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='pokes',
            field=models.ManyToManyField(to='landr.Poke'),
        ),
    ]
