# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landr', '0004_register_pokes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke',
            old_name='new_poker',
            new_name='poke_total',
        ),
        migrations.AlterField(
            model_name='poke',
            name='poked',
            field=models.CharField(max_length=255),
        ),
    ]
